name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple script
        run: |
          node --version
          npm --version
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python